from typing import Optional, Literal
from pydantic import BaseModel, Field

class TravelState(BaseModel):
    user_query: str
    city: Optional[str] = Field(default=None, description= "City from the user query")
    route: Optional[Literal["vector", "web"]] = Field(default=None, description= "chosen retrieval route = vector or web according to the city")
    city_summary: Optional[str] = Field(default= None, description="summary generated by llm")
    weather_forecast: list[dict] = Field(default_factory=list, description="weather forecast entries on the basis of time period/day")
    image_urls: list[str] = Field(default_factory=list, description="list of image urls relevant to the city")
    errors: list[str] = Field(default_factory=list, description="errors collected during graph execution which werent very fatal")